### ISSUE TITLE
What software was used to generate the images in the wiki?

### ISSUE THREAD

**Issue by vab2048** [pivotalsoftware/ESarch#52]
The wiki contains images such as the following:

![Transaction Aggregate](https://camo.githubusercontent.com/6355be5d28cc5e588a429695c1032bd4c66781f2/68747470733a2f2f696d6775722e636f6d2f66783879764f692e706e67 "Transaction Aggregate")

I would like to know: what software/process was used to generate this type of image?

**Comment by benwilcock** [comment]
Thanks for your question. To be honest, I'm not sure. I think it's probably regular office diagramming software, probably on Mac OS X. Perhaps @kbastani knows?
